# Generated by Django 5.0.1 on 2024-02-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouppay_app_api', '0002_remove_user_password_hash_alter_account_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='leader_user',
            new_name='leader_user_id',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='status',
            new_name='status_id',
        ),
        migrations.RenameField(
            model_name='groupmember',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='groupmember',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
