# Generated by Django 5.0.1 on 2024-02-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouppay_app_api', '0003_rename_leader_user_group_leader_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
