# Generated by Django 5.0.1 on 2024-02-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grouppay_app_api', '0004_alter_paymentstatus_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='description',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='paymentstatus',
            old_name='description',
            new_name='about',
        ),
    ]
