# Generated by Django 5.0.1 on 2024-02-25 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouppay_app_api', '0005_rename_description_group_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='grouppay_app_api.group'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='grouppay_app_api.user'),
        ),
    ]
