# Generated by Django 5.0.1 on 2024-02-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grouppay_app_api', '0007_alter_account_user_id_alter_group_leader_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='leader_user_id',
            new_name='leader_user',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='status_id',
            new_name='payment_status',
        ),
        migrations.RenameField(
            model_name='groupmember',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groupmember',
            old_name='user_id',
            new_name='user',
        ),
    ]
