# Generated by Django 5.0.1 on 2024-02-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouppay_app_api', '0008_rename_user_id_account_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentstatus',
            old_name='about',
            new_name='description',
        ),
        migrations.AddField(
            model_name='paymentstatus',
            name='status_code',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
