# Generated by Django 5.0.1 on 2024-02-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grouppay_app_api', '0009_rename_about_paymentstatus_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='payment_status',
            new_name='status',
        ),
    ]
