import type { Metadata } from "next";
import { Inter } from "next/font/google";


import Header from "@/components/header";
import Footer from "@/components/footer";

import "./globals.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Groupay App | Paying Made Easy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={`${inter.className }
      bg-blue-200 text-gray-950 relative pt-28 sm:pt-36 `}>
        
        
        <Header />
          
        {children}
        <Footer />
        

        
      </body>
    </html>
  )
}
